.SILENT:

default:
	echo creating a symbolic link to lab3b.py...
	ln -s lab3b.py lab3b
	chmod u+x lab3b

dist:
	tar -czvf lab3b-405118629.tar.gz Makefile README lab3b.py

clean:
	echo Cleaning directory...
	rm -f lab3b-405118629.tar.gz lab3b